### ISSUE TITLE
Path API returns inappropriate entity when "search" matches

### ISSUE THREAD

**Issue by Sunspark** [MauroDataMapper/mdm-core#188] opened 2021-11-12 13:52 UTC
**Describe the bug**
Given a structure as shown here:
![image](https://user-images.githubusercontent.com/5920776/141475873-c30568db-8375-45ce-b065-0acf70efc140.png)
Calling the API with URL:
{{base_url}}/dataModels/path/dm%3Amaurodatamapper%7Cdc%3Aapi_property
Returns the JSON snippet shown below, which details the entity at (maurodatamapper > core > api_property):
![image](https://user-images.githubusercontent.com/5920776/141477415-11b253c8-9b42-46c6-aa0f-f66675782b13.png)

**To Reproduce**
1. Given a Running Mauro instance
2. Given a data structure where an entity exists at different level in the hierarchy
3. When I ask the pathing API for a specific entity, using a name that exists at a different point in the hierarchy
4. Then it should return that specific entity, or 404
5. ERROR: an entity with the same name as was requested, but at a different point in the hierarchy is returned.

**Expected behavior**
The path API should return the entity described by the path, and 404 if that specific entity does not exist.

**Desktop (please complete the following information):**
 - OS: Win10, Azure VM. Running Mauro in Docker for Windows.
 - Browser: Chrome
 - Version:
     mauro-data-mapper:
        image: 'maurodatamapper/mauro-data-mapper:B4.10.0_F6.6.0'
        build:
            context: mauro-data-mapper
            args:
                MDM_APPLICATION_COMMIT: 4.10.0
                MDM_UI_COMMIT: 6.6.0
                ADDITIONAL_PLUGINS: "uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-database-sqlserver:5.1.0;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-csv:3.0.0;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-database-postgresql:4.0.0"
                MDM_UI_THEME_NAME: "default"

**Comment by aaronforshaw** [comment] 2021-11-26 09:59
@Sunspark is this a duplicate of #187 ?

**Comment by olliefreeman** [comment] 2021-11-30 10:46
@aaronforshaw yes I believe this will be solved by 187s solution

Duplicate of #187

**Comment by olliefreeman** [comment] 2021-11-30 10:47
Duplicate of #187

**Closed by olliefreeman** 2021-11-30 10:46 UTC
Labels: bug
