### ISSUE TITLE
Removing public flag from folder hides all models in it from the unauthenticated users (even if they have label public)

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-core#183] opened 2021-11-10 01:04 UTC
**Describe the bug**
Removing public flag from folder hides all modes in it from the unauthenticated users (even if they have label public)

**To Reproduce**
1. Create a Folder and set it as Public
2. Create a Data Model inside the folder, and set it to Public
3. Remove public flag from the Folder

**Current behavior**
Data Model still shows "publicly readable flag" 
But public user cannot see the folder or data model inside the folder

**Expected behavior**
Public user can still see the the data models that are configured as "public" at the data model level.

Note: I am not 100% sure whether the intent is to remove "publicly readable" flag for all child data models (things inside the folder) when removing this flag from the folder. If so, expected behavior would be that UI can show that these data models are not public anymore.

NOTE:
Similar behavior is when you add the public flag to the folder. All data models are shown to the end user no matter whether they are configured to be public or not. This one may be more straight forward because you may expect this behavior (overwrite by the parent), however this is not obvious when you remove the flag from the parent folder, because there is nothing you can see in the UI that tells you that that happened.

It looks like the "public" flag on data models gets updated when folder gets updated. However UI is not showing the right labels afterwards. 

**Screenshots**
This is how are data models configured:
![image](https://user-images.githubusercontent.com/81437684/141030164-09bea837-7d5f-496b-98a4-acfe77e3d59b.png)

1) If you set the folder as public, all data models show up to the public user whether or not they are public.

![image](https://user-images.githubusercontent.com/81437684/141030276-cb18ffac-4e83-4218-a9c6-942d6f0e2eb3.png)

2) If you remove the flag from the folder (please noteyou need to set the flag, and then remove the flag), none of the data models are visible to the public user, even if the data model label in the UI says they are public.

This is what the public user see: no folder no data models
![image](https://user-images.githubusercontent.com/81437684/141030394-8e441f9c-e1d1-4631-8585-7e5f611005d9.png)

This is what administrator sees: Its public, but noone can see it.  :-)
![image](https://user-images.githubusercontent.com/81437684/141030548-7fb1bfaf-502a-4faa-90da-232086c54b7d.png)

**Mauro version:**
MDM 4.10.0 UI: 6.6.0

**Additional context**

**Comment by olliefreeman** [comment] 2021-11-10 11:05
So permissions are inherited which means that whatever permissions you assign the folder are applied to the content of that folder, so the “note” behaviour is correct.

The reported bug though def shouldn’t be happening, as marking the folder performs
No actions on the content

**Comment by jelenadreskai** [comment] 2021-11-10 18:13
Hi @olliefreeman I am not sure if I follow second part.  :)

If permissions are inherited, when we remove the "public" flag from the folder, I see 2 possible behaviors:
1)  all public data models in that folder should become visible to the public user. 
2) all data models in that folder are not public anymore, however their UI label also needs to be updated (publicly available removed)

I would expect 1) intuitively.

**Comment by olliefreeman** [comment] 2021-11-30 10:43
Possibly linked to MC-9723

**Comment by olliefreeman** [comment] 2021-12-02 10:57
@aaronforshaw can you put some tests together for this, and if you can fix it without touching the mdm-security module then fix it. If its an issue inside the mdm-security module then can you detail why and I can fix it while I work on mc-9723

**Comment by aaronforshaw** [comment] 2021-12-02 16:53
I am not sure I understand the expected behaviour, so @olliefreeman please confirm if this is correct:

| |Folder Public|Folder Not Public|
|---|---|---|
|Data Model Public| 1. Folder is marked in database and UI as public. 2. Data Model is marked in database and UI as public. 3. Data Model is visible to unauthenticated user | 1. Folder is marked in database and UI as **not** public. 2. Data Model is marked in database and UI as public. 3. Data Model is **not** visible to unauthenticated user (because although the Data Model is marked as public, it inherits the **not** public setting of the Folder) |
|Data Model Not Public| 1. Folder is marked in database and UI as public. 2. Data Model is marked in database and UI as **not** public. 3. Data Model is visible to unauthenticated user (because although the Data Model is marked as **not** public, it inherits the public setting of the Folder) | 1. Folder is marked in database and UI as **not** public. 2. Data Model is marked in database and UI as public. 3. Data Model is **not** visible to unauthenticated user|

**Comment by olliefreeman** [comment] 2021-12-06 09:42
Okay so permissions are always inherited, however they can be overridden but only to "loosen" security, never to tighten.

SO in the table you have done

| |Folder Public|Folder Not Public|
|---|---|---|
|Data Model Public| 1. Folder is marked in database and UI as public. 2. Data Model is marked in database and UI as public. 3. Data Model is visible to unauthenticated user | 1. Folder is marked in database and UI as **not** public. (**however** it is visible in the tree as it contains public content[*see point 1*]) 2. Data Model is marked in database and UI as public. 3. Data Model **is** visible to unauthenticated user (because it overrides the Folder's setting) |
|Data Model Not Public| 1. Folder is marked in database and UI as public. 2. Data Model is marked in database and UI as **not** public. 3. Data Model is visible to unauthenticated user (because although the Data Model is marked as **not** public, it inherits the public setting of the Folder [*point 2*]) | 1. Folder is marked in database and UI as **not** public. 2. Data Model is marked in database and UI as **not** public. 3. Data Model is **not** visible to unauthenticated user|

1. in the event a folder contains public content when the tree is built the folder is added to the tree, however if the folder also contains non-public content then that content is NOT visible
2. security cannot be tightened as you descend

The inheritance is that you may make a folder public or readable by a group A and then create a second group B which contains some of the same users in group A. Group B is then given write access to 1 or 2 models and they can edit those models allowing all of group A to see the changes but not make their own.
You cannot however make the folder writable by Group A and then make a Group B which contains users of group A and make 1 or 2 models readable by group B. The users in group B will gain write access through their Group A access.

Hope that answers questions.

**Comment by aaronforshaw** [comment] 2021-12-06 16:28
@olliefreeman I think this needs a fix within mdm-security.

When the folder is updated with ```readableByEveryone: false```, the security policy manager for the not-logged in user is updated at: 

https://github.com/MauroDataMapper/mdm-core/blob/afc24bf7d1b2cce1fd36851cd6fb9945dcbdad2f/mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/policy/GroupBasedSecurityPolicyManagerService.groovy#L813-L815

In the call to ```updateAndStoreBuiltInSecurity```
https://github.com/MauroDataMapper/mdm-core/blob/afc24bf7d1b2cce1fd36851cd6fb9945dcbdad2f/mdm-security/grails-app/services/uk/ac/ox/softeng/maurodatamapper/security/policy/GroupBasedSecurityPolicyManagerService.groovy#L831-L850

```addAccess``` is false, and so two necessary virtual roles (one to read the folder and one to read the data model) are removed.

**Comment by olliefreeman** [comment] 2021-12-06 16:50
@aaronforshaw thanks

**Closed** 2021-12-13 12:27 UTC
Labels: bug
