### ISSUE TITLE
Pagination on Data Elements not working correctly

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#279] opened 2022-02-24 12:47 UTC
When looking for a data element to 'import', the UI calls:
`http://localhost:8080/api/dataModels/1dc596d5-a300-4a9e-ad69-4aa98e423215/dataClasses/fb17125a-258b-4fd3-ad75-b11eb26fc392/dataElements?max=20&offset=20`

And in this case only returned 3 results (there are many more than 40 data elements, so 20 should have been returned.
This may be related to ordering issues

<img width="1513" alt="Screenshot 2022-02-24 at 12 43 52" src="https://user-images.githubusercontent.com/1869668/155526808-90ca190f-c797-4236-bf69-969efa24f713.png">

**Comment by olliefreeman** [comment] 2022-02-24 13:52
ordering shouldnt have anything to do with pagination, pagination should be being passed off the to the db and we just get the amount of results requested....this is an odd one

**Comment by olliefreeman** [comment] 2022-02-24 14:04
@jamesrwelch i cant replicate this

**Comment by olliefreeman** [comment] 2022-02-24 14:25
also what DC has 8K DEs in it, the most ive got is Retired with 3K??

**Comment by olliefreeman** [comment] 2022-02-24 14:27
Ive tested this in a simple DB and also in 1 with 3 versions of the NHSDD, and i cannot replicate it, changed the offset and max values.

**Comment by jamesrwelch** [comment] 2022-02-24 14:41
It's an odd one - this is a recent ingest of the November DD, and you're right, I'm not sure why it has 8K DEs - maybe that's part of the problem.

**Comment by olliefreeman** [comment] 2022-02-24 15:07
can you give me the DM and DC label/path used in the url rather than the ids, so i can try and replicate it against what i have stored...and out of interest, in order:

1. reload the web browser page -> still an issue
2. stop and restart bootrun and reload -> still an issue??

**Comment by olliefreeman** [comment] 2022-02-24 15:14
also ... if it does replicate it, can you check the json thats actually being send from the backend to the browser

**Comment by olliefreeman** [comment] 2022-02-24 15:23
this isnt to do with pagination, this is to do with #226 and the imported items in this particular DM.

**Comment by olliefreeman** [comment] 2022-02-24 15:24
closing as Duplicate of #226

**Closed by olliefreeman** 2022-02-24 15:24 UTC
Labels: cant replicate
