### ISSUE TITLE
Smoke Testing: Server error message is displayed while trying to access a data model on Mauro

### ISSUE THREAD

**Issue by Jayafo** [MauroDataMapper/mdm-core#181] opened 2021-11-09 11:24 UTC
**Describe the bug**
When a user tries to access a data model in a folder on Mauro, Server error message is displayed. Environment administrator has investigated the issue but unsure what the issue is. 
**To Reproduce**
Steps to reproduce the behaviour:
1.	Go to Mauro version 4.11 (https://mauro-james-b4-11-0-f6-7-0.rost6.dev.dataproducts.nhs.uk/nhsd_mauro_dev/#/catalogue/dataModel/all)
2.	Enter valid credentials 
3.	Select Log in
4.	Select a folder to open 
5.	Select a data model 
6.	Server error message is displayed 

**Server error message**:
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "https://mauro-james-b4-11-0-f6-7-0.rost6.dev.dataproducts.nhs.uk/nhsd_mauro_dev/api/dataModels/3349a584-62bc-48d8-8437-0a46a76ee2a3/profiles/used",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://mauro-james-b4-11-0-f6-7-0.rost6.dev.dataproducts.nhs.uk/nhsd_mauro_dev/api/dataModels/3349a584-62bc-48d8-8437-0a46a76ee2a3/profiles/used: 500 OK",
  "error": {
    "status": 500,
    "reason": "Internal Server Error",
    "errorCode": "UEX--",
    "message": "JS-- - Unknown error",
    "path": "/api/dataModels/3349a584-62bc-48d8-8437-0a46a76ee2a3/profiles/used",
    "devMode": false,
    "version": "4.11.0",
    "exception": {
      "type": "NullPointerException",
      "stacktrace": [
        "uk.ac.ox.softeng.maurodatamapper.core.traits.service.DomainService$Trait$Helper.getDomainClass(DomainService.groovy:67)",
        "uk.ac.ox.softeng.maurodatamapper.core.traits.service.DomainService$Trait$Helper.handles(DomainService.groovy:71)",
        "uk.ac.ox.softeng.maurodatamapper.core.traits.service.DomainService$Trait$Helper.handles(DomainService.groovy:79)",
        "uk.ac.ox.softeng.maurodatamapper.profile.ProfileService$__tt__findServiceForMultiFacetAwareDomainType_closure23.doCall(ProfileService.groovy:129)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "uk.ac.ox.softeng.maurodatamapper.profile.ProfileService.$tt__findServiceForMultiFacetAwareDomainType(ProfileService.groovy:129)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)",
        "org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)",
        "grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)",
        "uk.ac.ox.softeng.maurodatamapper.profile.ProfileService.$tt__findMultiFacetAwareItemByDomainTypeAndId(ProfileService.groovy:135)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)",
        "org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)",
        "grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)",
        "uk.ac.ox.softeng.maurodatamapper.profile.ProfileController.usedProfiles(ProfileController.groovy:55)",
        "java.lang.invoke.VirtualHandle.invokeExact_thunkArchetype_L(VirtualHandle.java:130)",
        "java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)",
        "org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)",
        "org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)",
        "org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)",
        "org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)",
        "org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)",
        "org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)",
        "org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)",
        "org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)",
        "org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)",
        "org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)",
        "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)",
        "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)",
        "java.lang.Thread.run(Thread.java:831)"
      ]
    }
  }
}

**Expected behaviour**
User should be able to access data model in a folder 

**Screenshots**
![image](https://user-images.githubusercontent.com/87768436/140915647-32fa888b-921c-49e0-88da-f4efc538ba29.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jamesrwelch** [comment] 2021-11-09 21:33
After discussion via email, this looks like a repeat of #147 - due to an old, incompatible version of the MySQL plugin.  Awaiting feedback after plugin is updated.

**Comment by olliefreeman** [comment] 2021-11-09 22:17
I was wondering as we’d seen this sort of thing before, can we make sure that all the plugins used are updated as per the website documented versions/announce stream in zulip

**Comment by jamesrwelch** [comment] 2021-11-11 09:45
Duplicate of #147

**Closed by jamesrwelch** 2021-11-11 09:45 UTC
