### ISSUE TITLE
Error expanding subscribed catalogues

### ISSUE THREAD

**Issue by oughnic** [MauroDataMapper/mdm-core#186] opened 2021-11-11 18:55 UTC
**Describe the bug**
Error expanding a subscribed catalogue

``` javascript
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "https://demo.metadata.nhs.uk/nhsd_mauro_dev/api/subscribedCatalogues/616e025f-76ef-40fc-ad13-791de9e578e7/availableModels",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://demo.metadata.nhs.uk/nhsd_mauro_dev/api/subscribedCatalogues/616e025f-76ef-40fc-ad13-791de9e578e7/availableModels: 500 OK",
  "error": {
    "status": 500,
    "reason": "Internal Server Error",
    "errorCode": "UEX--",
    "message": "text",
    "path": "/api/subscribedCatalogues/616e025f-76ef-40fc-ad13-791de9e578e7/availableModels",
    "devMode": false,
    "version": "4.11.0",
    "exception": {
      "type": "NullPointerException",
      "message": "text",
      "stacktrace": [
        "java.util.Objects.requireNonNull(Objects.java:246)",
        "java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)",
        "java.time.OffsetDateTime.parse(OffsetDateTime.java:402)",
        "uk.ac.ox.softeng.maurodatamapper.federation.SubscribedCatalogueService$__tt__listPublishedModels_closure11$_closure12.doCall(SubscribedCatalogueService.groovy:130)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "uk.ac.ox.softeng.maurodatamapper.federation.SubscribedCatalogueService$__tt__listPublishedModels_closure11.doCall(SubscribedCatalogueService.groovy:124)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "uk.ac.ox.softeng.maurodatamapper.federation.SubscribedCatalogueService.$tt__listPublishedModels(SubscribedCatalogueService.groovy:123)",
        "jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
        "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)",
        "org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)",
        "grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)",
        "uk.ac.ox.softeng.maurodatamapper.federation.SubscribedCatalogueController.publishedModels(SubscribedCatalogueController.groovy:64)",
        "java.lang.invoke.VirtualHandle.invokeExact_thunkArchetype_L(VirtualHandle.java:130)",
        "org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)",
        "org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)",
        "org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)",
        "org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)",
        "org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)",
        "org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)",
        "org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)",
        "org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)",
        "org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)",
        "org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)",
        "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)",
        "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)",
        "java.lang.Thread.run(Thread.java:831)"
      ]
    }
  }
}
```

**To Reproduce**
1.  Add an API key to the source catalogue
2. Add the source catalogue as a subscribed catalogue in the destination catalogue
3. Expand the subscribed folders

**Comment by oughnic** [comment] 2021-11-11 18:57
To be assigned to @joe-crawford

**Comment by joe-crawford** [comment] 2021-11-12 11:53
I can confirm I can reproduce this on a local development instance when connecting to nhsd-test, I will investigate.

**Comment by joe-crawford** [comment] 2021-11-12 16:54
Issue is due to some null `datePublished` values on existing published models on the remote catalogue, raised as #189.

**Comment by joe-crawford** [comment] 2021-11-15 13:47
Hi @oughnic, this issue has now been resolved on nhsd-test by @jamesrwelch fixing some data from model importers. The underlying cause has been raised as #189 so I'll close this issue. Thanks.

**Closed by joe-crawford** 2021-11-15 13:47 UTC
Labels: bug
